<?php global $URL_PATH; ?>
<?php \dawfony\Ti::extend("view/MainView.phtml"); ?>
<?php \dawfony\Ti::startBlock("content"); ?>
<div class="principal">
<!-- clasificaciones Mustruo -->
  <div class="primerTercio">
    <header>
      <img src="<?= $URL_PATH?>/media/trofeo.png" id="trofeo">
      <span id="textoRanking"> Ranking de Mustruos </span>
      <div class="pestannas">
        <ul>
          <li id="semana"><a href="javascript:void(0)">semana</a></li>
          <li id="mes"><a href="javascript:void(0)">mes</a></li>
          <li id="anno"><a href="javascript:void(0)">año</a></li>
        </ul>
      </div>  
    </header>
    <section>
      <ol id="clasificacion"></ol>
    </section>
  </div>  
<!-- mesas -->
  <div class="segundoTercio">
    <section id="mesas"></section>
    <!-- boton nueva mesa-->
    <?php if (isset($_SESSION["login"])) : ?>
      <button id="nuevamesa">Nueva mesa</button>
    <?php endif; ?>
    <!-- chat-->
    <div>
      <section id="chat"></section>
      <input type="text" id="mensaje" placeholder="Escribe algo...">
      <button id="enviarmensaje">enviar</button>
    </div>
  </div>

  <div class="tercerTercio"><!--Inicio 3/3-->
  <!-- Usuarios online-->
    <div>
      <header>
        <h3>Usuarios online</h3>
      </header>
      <section>
        <ul id="usuariosonline"></ul>
      </section>
    </div>
<!-- Estadisticas-->
    <div>
      <header>
        <h3 id="encabezadoestadisiticas">Estadisticas</h3>
      </header>
      <section id="cuerpoestadisticas">
        Pincha sobre un usuario
      </section>
    </div>
  </div><!--Fin 3/3-->
<!-- modal de nueva mesa. TODO -->
<div class="modal fade" id="nuevamesamodal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content  bg-secondary">
      <div class="modal-header">
        <h5 class="modal-title font-weight-bold">Crear Nueva Mesa</h5>
      </div>
      <form action="<?= $URL_PATH ?>/mesa/nuevamesa" method="POST">

        <div class="modal-body">
          Vacas a ganar:
          <input type="radio" name="vacas" value="1">1
          <input type="radio" name="vacas" value="2" checked>2
          <input type="radio" name="vacas" value="3">3
          <br>
          Juegos a ganar por vaca:
          <input type="radio" name="juegos" value="2">2
          <input type="radio" name="juegos" value="3" checked>3
          <input type="radio" name="juegos" value="4">4
          <br>
          Puntos por juego:
          <input type="radio" name="puntos" value="30" checked>30
          <input type="radio" name="puntos" value="40">40
          <br>
          <input type="hidden" name="creador" value="<?= $usuario->login ?>">
          <button id="botpr" type="button" class="btn btn-danger" >Privada</button>
          <input id="clave" type="text" name="contrasenna" placeholder="Introduce clave">
          <input id="privacidad" type="hidden" name="privacidad" value="0">
        </div>
        <div class="modal-footer">
          <button type="submit" class="btn btn-light">Crear Mesa</button>
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
        </div>
      </form>
    </div>
  </div>
</div>

</div>
<!-- javascript -->
<script>
  var usuario = <?= json_encode($usuario) ?>;
  var path = "<?= $URL_PATH ?>";
  var arg = "<?=$arg?>";  
</script>
<script src="http://localhost:3300/socket.io/socket.io.js"></script>
<script src="js/lobby.js"></script>

<?php \dawfony\Ti::endBlock(); ?>
<?php \dawfony\Ti::endExtend(); ?>