<?php global $URL_PATH;?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- Propia hoja de estilos -->
    <link rel="stylesheet" href="css/main.css">
    <?php \dawfony\Ti::startBlock("extrahead"); ?>
    <?php \dawfony\Ti::endBlock() ?>
    <title>
        <?php \dawfony\Ti::startBlock("title"); ?>
        <?=$data["title"]?> - Mustruo
        <?php \dawfony\Ti::endBlock() ?>
    </title>
</head>
<body>
    <nav class="navbar bg-morado row">
        <div class="personalizarNav col-md-3">
            <?=$data["title"]?>
        </div>
        <!--LOGO-->
        <div class="personalizarNav col-md-4">
            <picture>
            <!--
                <source media="(min-width: 650px)" srcset="images/image-medium.png">
                <source media="(min-width: 465px)" srcset="images/image-small.png">
            -->    
                <img src="media/logoPrueba.png" >
            </picture>
        </div>
        <div class="col-md-5">
            <?php if (isset($_SESSION["login"])) : ?>
            <div class="float-right">
                <a class="perfil" href="<?= $URL_PATH ?>/perfil/<?= $_SESSION["login"] ?>">Perfil de <?= $_SESSION["login"] ?></a>
                <a class="btn boton-naranja ml-5" href="<?= $URL_PATH ?>/cerrarSesion">Cerrar Sesión</a>
            </div>    
            <?php elseif (isset($registro)) : ?>
                <a class="btn boton-naranja float-right" href="<?= $URL_PATH ?>/">Volver a Lobby</a>
            <?php else : ?>
                <div class="form-inline float-right">
                    <input type="text" class="form-control mr-sm-2" id="login" name="login" placeholder="login">
                    <input type="password" class="form-control mr-sm-2" id="contrasenna" name="contrasenna" placeholder="******">
                    <div class="bloqueRegistro">
                        <input type="button" class="btn boton-naranja" onclick="comprobarSesion()" value="Iniciar Sesión">
                        <a href="<?= $URL_PATH ?>/registrate">Regístrate</a>
                    </div>
                </div>
                <script>
                    var URL_PATH = '<?= $URL_PATH ?>';
                </script>
                <script src="<?= $URL_PATH ?>/js/comprobarSesion.js"></script>
            <?php endif; ?> 
        </div>
    </nav>
    <div class="container">
    <?php \dawfony\Ti::startBlock("content"); ?>
    <?php \dawfony\Ti::endBlock() ?>
    </div>
</body>
</html>