<?php global $URL_PATH; ?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- Propia hoja de estilos -->
    <link rel="stylesheet" href="<?= $URL_PATH ?>/css/main.css">
    <title>
        <?= $data["title"] ?> - Mustruo
    </title>
</head>

<body>
    <div class="principalMesa">
        <!--Partida-->
        <div class="partida">
            <!--Puntos Partida-->
            <div class="puntosPartida">
                <div class="tablaPuntos">
                    <div class="ocultarDeTabla"></div>
                    <div><span>Puntos</span></div>
                    <div>Juegos</div>
                    <div>Vacas</div>
                    <div><?=$usuario->login?> / <?=$compannero->login?></div>
                    <div id="puntosa">3</div>
                    <div id="juegosa">0</div>
                    <div id="vacasa">0</div>
                    <div><?=$rivalDer->login?> / <?=$rivalIzq->login?></div>
                    <div id="puntosb">8</div>
                    <div id="juegosb">0</div>
                    <div id="vacasb">0</div>
                </div>
            </div>
            <!--Cuadro Envites-->
            <div class="cuadroEnvites">
                <div>
                    <span>Grande: <span id="grande">-</span></span>
                </div>
                <div>
                    <span>Chica: <span id="chica">-</span></span>
                </div>
                <div>
                    <span>Pares: <span id="pares">-</span></span>
                </div>
                <div>
                    <span>Juego: <span id="juego">-</span></span>
                </div>
                <div>
                    <span>Punto: <span id="punto">-</span></span>
                </div>
            </div>
            <!--Cuenta Atras-->
            <div class="reloj hidden" id="reloj">10</div>
            <!--Interacción-->
            <div class="interaccion" id="interaccion">
                <div class="hidden" id="haymus">
                    <div class="serieInteraccion">
                        <div></div>
                        <div class="serieVertical">
                            <button id="mus" class="btn boton-marron">Mus</button>
                            <button id="nomus" class="btn boton-marron">No Mus</button>
                        </div>
                    </div>
                </div>
                <div class="hidden" id="nohayEnvite">
                    <div class="serieInteraccion">
                        <div class="serieHorizontal">
                            <button id="menos" class="btn boton-marron">-</button>
                            <div id="textoEnvidar">2</div>
                            <button id="mas" class="btn boton-marron">+</button>
                        </div>
                        <div class="serieVertical">
                            <button id="envidar" class="btn boton-marron">Envido 2</button>
                            <button id="ordago" class="btn boton-marron">Órdago</button>
                            <button id="paso" class="btn boton-marron">Paso</button>
                        </div>
                    </div>
                </div>
                <div class="hidden" id="hayEnvite">
                    <div class="serieInteraccion">
                        <div class="serieHorizontal">
                            <button id="haymenos" class="btn boton-marron">-</button>
                            <div id="haytextoEnvidar">2</div>
                            <button id="haymas" class="btn boton-marron mas">+</button>
                        </div>
                        <div class="serieVertical">
                            <button id="hayenvidar" class="btn boton-marron">Envido 2</button>
                            <button id="hayordago" class="btn boton-marron">Órdago</button>
                            <button id="hayquiero" class="btn boton-marron">Quiero</button>
                            <button id="haynoquiero" class="btn boton-marron">No Quiero</button>
                        </div>    
                    </div>
                </div>
                <div class="hidden" id="hayordago">
                    <div class="serieInteraccion">
                        <button id="quiero" class="btn boton-marron">Quiero</button>
                        <button id="noquiero" class="btn boton-marron">No Quiero</button>
                    </div>
                </div>
            </div>
            
            <!--Usuarios-->
            <!--Mi usario
            <div class="usuario bloqueUsu">
                <img src="<?= $URL_PATH ?>/media/avatares/<?= $usuario->imagen ?>">
                <span><?= $usuario->login ?></span>
            </div>-->
            <!--Comapannero-->
            <div class="compannero bloqueUsu">
                <img src="<?= $URL_PATH ?>/media/avatares/<?= $compannero->imagen ?>">
                <div id="compannero"><?= $compannero->login ?></div>
            </div>
            <!--RivalDer-->
            <div class="rivalDer bloqueUsu">
                <img src="<?= $URL_PATH ?>/media/avatares/<?= $rivalDer->imagen ?>">
                <div id="rivalder"><?= $rivalDer->login ?></div>
            </div>
            <!--RivalIIzq-->
            <div class="rivalIzq bloqueUsu">
                <img src="<?= $URL_PATH ?>/media/avatares/<?= $rivalIzq->imagen ?>">
                <div id="rivalizq"><?= $rivalIzq->login ?></div>
            </div>
            <!--Tapete-->
            <div class="mesaJuego">
                <div class="tapete"></div>
            </div>
            <!--Puerta Salir-->
            <img src="<?= $URL_PATH ?>/media/flecha.png" class="flecha" id="salir" title="Abandonar partida">
            <img src="<?= $URL_PATH ?>/media/salir.png" class="puerta" id="salir" title="Abandonar partida">
        </div>
        <!--Chat y estadisticas-->
        <div class="chatStats">
            <!--1/2-->
            <div class="chatusu">
            <!--Chat-->
            <div class="chatmesa">
                    <section id="chat" class="text scroll"></section>
                    <div class="sendText">
                        <input type="text" id="mensaje" placeholder="Escribe algo...">
                        <button id="enviarmensaje" class="btn boton-morado">enviar</button>
                    </div>
            </div>
            <!--Usuarios online-->
            <div class="usuariosmesa">
                <header class="headerUsu">
                    <span class="textoHeader">Usuarios</span>
                </header>
                <section class="usus">
                    <ul id="usuariosonline"></ul>
                </section>
            </div>
            </div>
            <!--2/2-->
            <div class="stats">
                <header class="headerStats">
                    <span class="textoHeader">Estadísticas <span id="usuestadisticas"></span></span>
                </header>
                <section class="tablaEstadisticas">
                    <div></div>
                    <div>Jugados</div>
                    <div>Ganados</div>
                    <div>Juegos</div>
                    <div id="juegosJugados"></div>
                    <div id="juegosGanados"></div>
                    <div>Vacas</div>
                    <div id="vacasJugadas"></div>
                    <div id="vacasGanadas"></div>
                </section>
                <span class="abandonos">Abandonos: <span id="abandonos"></span></span>
            </div>
        </div>
    </div>
    <!--SCRIPT-->
    <script>
        var usuario = <?= json_encode($usuario) ?>;
        var path = "<?= $URL_PATH ?>";
        var mesa = <?=json_encode($mesa)?>;
    </script>
    <script src="<?= $URL_PATH ?>/js/rangoEnvite.js"></script>
    <script src="http://localhost:3333/socket.io/socket.io.js"></script>
    <script src="<?= $URL_PATH ?>/js/mesa.js"></script>
</body>
</html>