<?php global $URL_PATH;?>
<?php \dawfony\Ti::extend("view/MainView.phtml"); ?>
<?php \dawfony\Ti::startBlock("content"); ?>
<div class="container">
<form id="registro" action="registrate" method="POST" enctype="multipart/form-data">
    <div class="form-group">
        <label for="login">Login:</label>
        <input type="text" class="form-control" id="login" name="login">
        <small id="errorLogin"></small>
    </div>
    <div class="form-group">
        <label for="contrasenna">Contraseña:</label>
        <input type="password" class="form-control" id="contrasenna" name="contrasenna">
    </div>
    <div class="form-group">
        <label for="repitecontrasenna">Repite contraseña:</label>
        <input type="password" class="form-control" id="repitecontrasenna">
        <small id="errorContrasenna"></small>
    </div>
    <div class="form-group">
        <label for="email">Email:</label>
        <input type="text" class="form-control" id="email" name="email" name="email">
        <small id="errorEmail"></small>
    </div>
    <div class="custom-file">
        <input type="file" class="custom-file-input" id="avatar" name="avatar">
        <label class="custom-file-label" for="avatar" id="valueAvatar">Elige una foto de perfil...</label>
        <small id="errorAvatar">*Si no se te pondra una por defecto</small>
    </div>
    <input type="button" onclick="comprobarRegistro()" class="btn boton-naranja float-right" value="Registrarte!">
    <input type="submit" id="enviar" style="visibility:hidden">
</form>
</div>
<script>
var URL_PATH = '<?= $URL_PATH ?>';
</script>
<script src="<?= $URL_PATH ?>/js/comprobarRegistro.js"></script>
<?php \dawfony\Ti::endBlock(); ?>
<?php \dawfony\Ti::endExtend(); ?>